---
title: "Finseth Ren Figures"
author: "Ren Henry-Mitchell"
date: "2026-05-20"
output: html_document
---

```{r}
#libraries
library(pheatmap)
library(RColorBrewer)
library(gprofiler2)
library(tidyverse)
BiocManager::install("edgeR")
library(edgeR)
library(clusterProfiler)
library(VennDiagram) 
library(edgeR)
library(clusterProfiler)
library(ggplot2)
library(viridis)
library(stringr)
library(vegan)
#library(vegan3d)
library(scatterplot3d)
library(eulerr)
#running with errors, did some sleuthing and it seems like this will still work, the openGL error this mentions is only relevent for creating big interactive graphs
```

```{r}
#Reading raw files
Mimulus_Sample_Info <- read_csv("Mimulus_Sample_Info.csv")
mim_table <- read_table("all_counts3.out", col_names = TRUE)
```

```{r}
###reordering dge.subsets and testDGE. refactoring necessary bc testDGE sorts numerically
mimData <- mim_table[,2:dim(mim_table)[2]]
mimAnnotation <- read.csv("Mimgutt_annotations.csv", header = T)
mimGroups <- Mimulus_Sample_Info$Group
mimGroups

testDGE <- DGEList(counts = mimData, group = factor(mimGroups), genes = mimAnnotation)
## correcting groups to account for numerical sorting of plant # in testDGE samples not matching mimulus_sample_info order (54 in heat treatment, 60 in cold) 
testDGE$samples$group[9] <- factor("An_F1_H")
testDGE$samples$group[21] <- factor("An_F1_C")
testDGE$samples$group[10] <- factor("Bu_F1_H")
testDGE$samples$group[22] <- factor("Bu_F1_C")
testDGE$samples$group[11] <- factor("Le_F1_H")
testDGE$samples$group[23] <- factor("Le_F1_C")
testDGE$samples$group[12] <- factor("Ov_F1_H")
testDGE$samples$group[24] <- factor("Ov_F1_C")
```

```{r}
## legacy subsets --> finseth said not to do it this way, bc we lose power
dge.subset_anth <- testDGE[,which(testDGE$samples$group == "An_F1_C" | testDGE$samples$group == "An_F1_H")]

dge.subset_leaf <- testDGE[,which(testDGE$samples$group == "Le_F1_C" | testDGE$samples$group == "Le_F1_H")]
dge.subset_ovary <- testDGE[,which(testDGE$samples$group == "Ov_F1_C" | testDGE$samples$group == "Ov_F1_H")]
dge.subset_bud <- testDGE[,which(testDGE$samples$group == "Bu_F1_C" | testDGE$samples$group == "Bu_F1_H")]
```

```{r}
###Apply + keep step + columns###
apply(testDGE$counts, 2, sum)
apply(dge.subset_anth$counts, 2, sum)
apply(dge.subset_leaf$counts, 2, sum)
apply(dge.subset_ovary$counts, 2, sum)
apply(dge.subset_bud$counts, 2, sum)

keep <- rowSums(cpm(testDGE)> 20) >= 2
keep.anth <- rowSums(cpm(dge.subset_anth)> 20) >= 2
keep.leaf <- rowSums(cpm(dge.subset_leaf)> 20) >= 2
keep.ovary <- rowSums(cpm(dge.subset_ovary)> 20) >= 2
keep.bud <- rowSums(cpm(dge.subset_bud)> 20) >= 2

testDGE <- testDGE[keep,]

dge.subset_anth <- dge.subset_anth[keep.anth,]
dge.subset_leaf <- dge.subset_leaf[keep.leaf,]
dge.subset_ovary <- dge.subset_ovary[keep.ovary,]
dge.subset_bud <- dge.subset_bud[keep.bud,]

testDGE$samples$lib.size <- colSums(testDGE$counts)

dge.subset_anth$samples$lib.size <- colSums(dge.subset_anth$counts)
dge.subset_leaf$samples$lib.size <- colSums(dge.subset_leaf$counts)
dge.subset_ovary$samples$lib.size <- colSums(dge.subset_ovary$counts)
```

```{r}
###Bar plots###
barplot(testDGE$samples$lib.size*1e-6, ylab="Library size (millions)",names=rownames (testDGE$samples))
```
```{r}
###calc norm factors ###
testDGE <-  calcNormFactors(testDGE)
dge.subset_anth <- calcNormFactors(dge.subset_anth)
dge.subset_leaf<- calcNormFactors(dge.subset_leaf)
dge.subset_ovary <- calcNormFactors(dge.subset_ovary)
dge.subset_bud <- calcNormFactors(dge.subset_bud)
```

```{r}
### mds plots ###
#plotMDS.DGEList(testDGE, method="bcv", col=as.numeric(testDGE$samples$group), dim.plot = c(1,2))

#label = testDGE$samples$group
```


```{r}
alltissue.cpmMatrix <- cpm(testDGE, log = TRUE)
sample_matrix <- t(alltissue.cpmMatrix)
nmds_3d <- metaMDS(sample_matrix, distance = "bray", k = 3, trymax = 100)
nmds_3d$stress

nmds_points <- as.data.frame(nmds_3d$points)
colnames(nmds_points) <- c("NMDS1", "NMDS2", "NMDS3")
```

```{r}
## assuming you have a dataframe called 'metadata' with a column 'Group'
nmds_points$SampleID <- rownames(nmds_points)
#nmds_points$Group <- Mimulus_Sample_Info$Group
nmds_points$Group <- testDGE$samples$group

#colors <- c("lightskyblue1", "lightskyblue2", "lightskyblue3","lightskyblue4", "goldenrod1","goldenrod2", "goldenrod3","goldenrod4")
colors <- c("lightskyblue1","goldenrod1","lightskyblue2","goldenrod2","lightskyblue3","goldenrod3","lightskyblue4","goldenrod4")

##for some reason, this only works when this is stored as a new object, not as a modification to "colors"
group_colors <- colors[as.numeric(as.factor(nmds_points$Group))]
color_play <- as.factor(nmds_points$Group)
legend_guide <- levels(color_play)

# create static 3D plot
sample.3d.plot <- scatterplot3d(x = nmds_points$NMDS1, 
              y = nmds_points$NMDS2, 
              z = nmds_points$NMDS3,
              color = group_colors,
              pch = 19,
              xlab = "NMDS1",
              ylab = "NMDS2",
              zlab = "NMDS3",
              main = "3D NMDS Plot")
legend(x = 4, y = 7,
       legend = legend_guide,
       col = colors, 
       pch = 16, 
       inset = 0.05, 
       xpd = TRUE)
```


```{r}
#plotMDS(dge.subset_anth, method="bcv", col=as.numeric(dge.subset_anth$samples$group), label = dge.subset_anth$samples$group, dim.plot = c(1,2))
```

```{r}

#plotMDS(dge.subset_leaf, method="bcv", col=as.numeric(dge.subset_leaf$samples$group), label =dge.subset_leaf$samples$group, dim.plot = c(1,2))
```

```{r}
#plotMDS(dge.subset_ovary, method="bcv", col=as.numeric(dge.subset_ovary$samples$group), label =dge.subset_ovary$samples$group, dim.plot = c(1,2))
```

```{r}
#rebuilding design to use makeContrast filters
group <- factor(c("An_F1_C","An_F1_H","Bu_F1_C","Bu_F1_H","Le_F1_C","Le_F1_H","Ov_F1_C","Ov_F1_H"))
design.alltissue <-  model.matrix(~0+group, data = testDGE$samples)
design.alltissue
testDGE <- estimateDisp(testDGE,design.alltissue)
testDGE <- calcNormFactors(testDGE)
testDGE <- estimateDisp(testDGE, design.alltissue)
colnames(design.alltissue) <- levels(testDGE$samples$group)


# bringing back these for clarity of the components used to create these
Mimulus_Sample_Info <- read_csv("Mimulus_Sample_Info.csv")
mim_table <- read_table("all_counts3.out", col_names = TRUE)
mimGroups <- Mimulus_Sample_Info$Group

all.tissuecontrasts <- makeContrasts(HvsCanther=An_F1_H-An_F1_C, HvsCbud=Bu_F1_H-Bu_F1_C, HvsCovary=Ov_F1_H-Ov_F1_C, HvsCleaf=Le_F1_H-Le_F1_C, levels=design.alltissue)

fit <- glmQLFit(testDGE, design.alltissue)

qlf.overall <- glmQLFTest( fit, contrast= all.tissuecontrasts)
overallTags <- topTags(qlf.overall, n = Inf, adjust.method = "BH")
qlf.Anther <- glmQLFTest(fit, contrast=all.tissuecontrasts[,"HvsCanther"])
antherTags<- topTags(qlf.Anther, n = Inf, adjust.method = "BH")
qlf.Bud <- glmQLFTest(fit, contrast=all.tissuecontrasts[,"HvsCbud"])
budTags <- topTags(qlf.Bud, n = Inf, adjust.method = "BH")
qlf.ovary <- glmQLFTest(fit, contrast=all.tissuecontrasts[,"HvsCovary"])
ovaryTags <- topTags(qlf.ovary, n = Inf, adjust.method = "BH")
qlf.leaf <- glmQLFTest(fit, contrast=all.tissuecontrasts[,"HvsCleaf"])
leafTags <- topTags(qlf.leaf, n = Inf, adjust.method = "BH")
```

```{r}
### designing count data frame for clair
grouping <- testDGE$samples$group
tissue.list <- c("An", "Bu", "Le", "Ov", "An", "Bu", "Le", "Ov", "An", "Bu", "Le", "Ov", "An", "Bu", "Le", "Ov", "An", "Bu", "Le", "Ov", "An", "Bu", "Le", "Ov", "An", "Bu", "Le", "Ov", "An", "Bu", "Le", "Ov")
uprCountanalysis <- t(testDGE$counts)
uprCountanalysis <- as.data.frame(uprCountanalysis)
uprCountanalysis <- uprCountanalysis |> 
  mutate(group=grouping) |> 
  mutate(tissue = as.factor(tissue.list)) 
  


```




```{r}
#Building design — legacy, updated to use makeContrasts instead
design <-  model.matrix(~0+group, data = testDGE$samples)
design.anth <- model.matrix(~0+group, data = dge.subset_anth$samples)
colnames(design.anth) <- levels(dge.subset_anth$samples$group)

design.leaf <- model.matrix(~0+group, data=dge.subset_leaf$samples)
colnames(design.leaf) <- levels(dge.subset_leaf$samples$group)

design.ovary <- model.matrix(~0+group, data=dge.subset_ovary$samples)
colnames(design.ovary) <- levels(dge.subset_ovary$samples$group)

design.bud <- model.matrix(~0+group, data=dge.subset_bud$samples)
colnames(design.bud) <- levels(dge.subset_bud$samples$group)

###estimate dispersion
dge.subset_anth <- estimateDisp(dge.subset_anth, design.anth)
dge.subset_leaf <- estimateDisp(dge.subset_leaf, design.leaf)
dge.subset_ovary <- estimateDisp(dge.subset_ovary, design.ovary)
dge.subset_bud <- estimateDisp(dge.subset_bud, design.bud)

```

```{r}
### LEgacy <- creating dge alias to run exact test ###
etTestDGE <- testDGE
etTestDGE$samples$condition <- ifelse(grepl("_H$", etTestDGE$samples$group), "H", "C")
etTestDGE$samples$condition <- factor(etTestDGE$samples$condition)
etTestDGE <- calcNormFactors(etTestDGE)
etTestDGE <- estimateDisp(etTestDGE)
etTestDGE$samples$group <- factor(etTestDGE$samples$condition)
et <- exactTest(etTestDGE, pair = c("C", "H"))
results <- topTags(et, n = Inf)$table
```

```{r}
###Legacy <- et for the rest of tissue groups and isolating/filtering for top tags###
et.anth.hvc <- exactTest(dge.subset_anth, pair = c("An_F1_C","An_F1_H"))
et.leaf.hvc <- exactTest(dge.subset_leaf, pair = c("Le_F1_C", "Le_F1_H"))
et.ovary.hvc <- exactTest(dge.subset_ovary, pair = c ("Ov_F1_C", "Ov_F1_H"))
et.bud.hvc <- exactTest(dge.subset_bud, pair = c ("Bu_F1_C", "Bu_F1_H"))

all.DGE <- topTags(et, n=nrow(et$table))$table
tbl.anth_hvc <- topTags(et.anth.hvc, n=nrow(et.anth.hvc$table))$table
tbl.leaf_hvc <- topTags(et.leaf.hvc,n=nrow(et.leaf.hvc))$table
tbl.ovary_hvc <- topTags(et.ovary.hvc, n=nrow(et.ovary.hvc))$table
tbl.bud_hvc <- topTags(et.bud.hvc, n=nrow(et.bud.hvc))$table

#Legacy <- final tables of all differentially expressed genes
is.de.leaf_hvc <-  decideTests.DGEExact(et.leaf.hvc,p=0.05)
is.de.anth_hvc <-  decideTests.DGEExact(et.anth.hvc,p=0.05)
is.de.ovary_hvc <- decideTests.DGEExact(et.ovary.hvc,p=0.05)
is.de.bud_hvc <- decideTests.DGEExact(et.bud.hvc,p=0.05)
```


```{r}
### venn diagram ###
head(tbl.anth_hvc)
anth.DE <- subset(tbl.anth_hvc, tbl.anth_hvc$FDR < 0.05)
head(anth.DE)

ov.DE <- subset(tbl.ovary_hvc, tbl.ovary_hvc$FDR < 0.05)
leaf.DE <- subset(tbl.leaf_hvc, tbl.leaf_hvc$FDR < 0.05)

anth.up <- subset(anth.DE, anth.DE$logFC > 0)
anth.down <- subset(anth.DE, anth.DE$logFC < 0)

venn.diagram(
  x = list(anther = anth.DE$GENE, ovary = ov.DE$GENE, leaf = leaf.DE$GENE),
  filename = "VennDiagram2.png",
  col = "transparent", 
  fill = viridis(3),
  alpha = 0.5,
  label.col = c("black", "black", "black", "black", "black", "black", "black"),
  cex = 1.5,
  fontfamily = "Helvetica",
  cat.fontfamily = "Helvetica",
  fontface = "bold",
  cat.default.pos = "text",
  cat.col = c("black", "black", "black"),
  cat.cex = 2,
  cat.dist = c(0.05, 0.05, 0.05),
  cat.pos = c(10, 10, 10)
)
 
### Exactracting a table of overlapping genes###
anther <- anth.DE$GENE
ovary  <- ov.DE$GENE
leaf   <- leaf.DE$GENE

common_all <- Reduce(intersect, list(anther, ovary, leaf))
anth_ovary <- setdiff(intersect(anther, ovary), leaf)
anth_leaf <- setdiff(intersect(anther, leaf), ovary)
ovary_leaf <- setdiff(intersect(ovary, leaf), anther)
anth_only <- setdiff(anther, union(ovary, leaf))

ovary_only <- setdiff(ovary, union(anther, leaf))
leaf_only <- setdiff(leaf, union(anther, ovary))

write.csv(common_all, "common_all_genes.csv", row.names = FALSE)

```


```{r}
###Barplot + pairwise  ###
qlf.Anther$coefficients


total_anther <- length(qlf.Anther$genes$GENE)
total_ovary <- length(qlf.ovary$genes$GENE)
total_leaf <- length(qlf.leaf$genes$GENE)
total_bud <- length(qlf.Bud$genes$GENE)

anth.up <- subset(qlf.Anther$genes, qlf.Anther$table$logFC > 2)
anth.down <- subset(qlf.Anther$genes, qlf.Anther$table$logFC < -2)
anth_up_num <- length(anth.up$GENE)
anth_down_num <- length(anth.down$GENE)


ov.up <- subset(qlf.ovary$genes, qlf.ovary$table$logFC > 2)
ov.down <- subset(qlf.ovary$genes, qlf.ovary$table$logFC< -2)
ov_up_num <- length(ov.up$GENE)
ov_down_num <- length(ov.down$GENE)


leaf.up <- subset(qlf.leaf$genes, qlf.leaf$table$logFC > 2)
leaf.down <- subset(qlf.leaf$genes, qlf.leaf$table$logFC < -2)
leaf_up_num <- length(leaf.up$GENE)
leaf_down_num <- length(leaf.down$GENE)

bud.up <- subset(qlf.Bud$genes, qlf.Bud$table$logFC > 2)
bud.down <- subset(qlf.Bud$genes, qlf.Bud$table$logFC < -2)
bud_up_num <- length(bud.up$GENE)
bud_down_num <- length(bud.down$GENE)

x <- c(anth_up_num, anth_down_num, ov_up_num, ov_down_num, leaf_up_num, leaf_down_num, bud_up_num, bud_down_num) 
n <- c(total_anther, total_anther, total_ovary, total_ovary,  total_leaf, total_leaf, total_bud, total_bud)
ov_up_num/total_ovary
ov_down_num/total_ovary
anth_up_num/total_anther
anth_down_num/total_anther
leaf_up_num/total_leaf
leaf_down_num/total_leaf
bud_up_num/total_bud
bud_down_num/total_bud

pairwise.prop.test(x, n)

part <- c("Leaf", "Leaf", "Anther", "Anther", "Ovary", "Ovary", "Bud", "Bud")
up_down <- c("Up Regulated", "Down Regulated", "Up Regulated", "Down Regulated", "Up Regulated", "Down Regulated", "Up Regulated", "Down Regulated")
values <- c(leaf_up_num/total_leaf, leaf_down_num/total_leaf, anth_up_num/total_anther, anth_down_num/total_anther, ov_up_num/total_ovary, ov_down_num/total_ovary, bud_up_num/total_bud, bud_down_num/total_bud)
part <- factor(part, levels = c("Leaf", "Anther", "Ovary", "Bud"))

df <- data.frame(
  part = part,
  up_down = up_down,
  values = values
)
head(df)

ggplot(df, aes(x = part, y = values, fill = up_down)) +
  geom_bar(position = "dodge", stat = "identity") +
  scale_fill_viridis_d() +
  labs(
    x = "Tissue",
    y = "Proportion of Total Genes",
    fill = "Direction"
  ) +
  theme_minimal()
```



```{r}
## all tissue venn diagrams, updated correct now
anth.venn <- subset(antherTags$table$GENE, antherTags$table$FDR < 0.05)

bud.venn <- subset(budTags$table$GENE, budTags$table$FDR < 0.05)

leaf.venn <- subset(leafTags$table$GENE, leafTags$table$FDR < 0.05)
ovary.venn <- subset(ovaryTags$table$GENE, ovaryTags$table$FDR < 0.05)

## nonproportional venn diagrams
venn.diagram(
  x = list(
    anther = anth.venn,
    ovary = ovary.venn,
    leaf = leaf.venn,
    bud = bud.venn
    ),
  filename = "VennDiagramTissueOverlap.png",
  col = "transparent", 
  fill = viridis(4),
  alpha = 0.5,
  label.col = "black",
  cex = 1.5,
  fontfamily = "Helvetica",
  cat.fontfamily = "Helvetica",
  fontface = "bold",
  cat.default.pos = "text",
  cat.col = c("black", "black", "black", "black"),
  cat.cex = 2,
  cat.dist = c(0.05, 0.05, 0.05, 0.05),
  cat.pos = c(10, 10, 10, 10))


### making augmented venn diagrams with de threshold
anth.logfc <- antherTags$table |> 
  mutate(abs_logFC=abs(logFC)) 
anth.euler <- subset(antherTags$table$GENE, antherTags$table$FDR < 0.05 & anth.logfc$abs_logFC>2)


bud.logfc <- budTags$table |> 
  mutate(abs_logFC=abs(logFC)) 
bud.euler <- subset(budTags$table$GENE, budTags$table$FDR < 0.05 & bud.logfc$abs_logFC>2)


leaf.logfc <- leafTags$table |> 
  mutate(abs_logFC=abs(logFC)) 
leaf.euler <- subset(leafTags$table$GENE, leafTags$table$FDR < 0.05 & leaf.logfc$abs_logFC>2)

ovary.logfc <- ovaryTags$table |> 
  mutate(abs_logFC=abs(logFC))
ovary.euler <- subset(ovaryTags$table$GENE, ovaryTags$table$FDR < 0.05 & ovary.logfc$abs_logFC>2)


##euler venn diagram (proportional circle sizes)

allTissueLists <- list(
  anther = anth.euler,
    leaf = leaf.euler,
    bud = bud.euler,
  ovary = ovary.euler
)

fit.allTissue <- euler(allTissueLists, 
             shape = "circle", 
             control = list(extra_loops = 50, maxeval = 2000))

summary(fit.allTissue)

grid.newpage()
pushViewport(viewport(width = 1.5, height = 1.5))

euler.colorlist <- c("#fde725", "#28ae80", "#375b8d", "#440154")

plot(fit.allTissue, quantities = TRUE, fills = (fill = euler.colorlist), labels = TRUE, alpha = .7,)


plot(fit.allTissue, quantities = TRUE, fills = (fill = euler.colorlist), labels = FALSE, alpha = .7,)


```




```{r}
## matching tissue specific diferentialy expressed genes with loci of interest chromosome 11

#note on calculating
#normalizes format to facilitate joining
overallDEGs.mapping <- as_tibble(overallTags$table)
overallDEGs.mapping <- overallDEGs.mapping |> 
  mutate(GENE= str_remove(GENE,".v3.1")) |> 
  mutate(GENE= str_remove(GENE," "))


#inner join was a success story!


View(chr11Overlap)


chr11GenesBase <- read.csv("TableS6_genes_CHR11_v4.csv", header = T, sep = ",")
chr11GenesBase <- chr11GenesBase |> 
  mutate(stratum=as.factor(stratum))
chr11GenesIM62v4 <- chr11GenesBase |> filter(IM62v4 != "x")

chr11Overlap <- inner_join(chr11GenesIM62v4, overallDEGs.mapping, by = join_by(IM62v4 == GENE))
chr11total <- nrow(chr11GenesIM62v4)




#for loop to create dfs of the whole crhomosome sorted by strata 
#chr11GenesIM62v4 <- chr11GenesIM62v4 |> 
 # mutate(stratum = case_when(
 #   IM62v4 == "out" ~ "prehap-out"
 # ))
 # mutate(stratum=as.factor(stratum)) 
  
chr11Overlap <- chr11Overlap |> 
  mutate(stratum=as.factor(stratum)) 
  
  
for (lvl in levels(chr11Overlap$stratum)) {
  # Dynamically generate a name for the dataframe
  df_name <- paste0("chr11_", lvl)
  
  # Filter the data
  sub_df <- chr11Overlap[chr11Overlap$stratum == lvl, ]
  
  # Assign the data to the generated name in the global environment
  assign(df_name, sub_df)
}



```

```{r}
#### Pairwise analysis, marking by chromosome stratum in character 11
#chr11AntherOverlap
#NROW all caps syntax is purposeful, unfortunately Biocmanger masks nrow funtion in a way that was leading to the funciton to fail, the all caps operator refers back ot the unmasked base function NROW
#Correcting here now, total # should be calculted from chr11IM62v4


out.chr11Overlap <- chr11Overlap |> 
  filter(stratum=="out")

out.total <- NROW(chr11_out)
  

hap.chr11Overlap<- chr11Overlap |> 
  filter(stratum=="hap")

hap.total <- NROW(chr11_hap)

hapEDG.chr11Overlap <-  chr11Overlap |>  
  filter(stratum == "hap-EDG")

hapEDG.total <- NROW(`chr11_hap-EDG`)

inv11a.chr11Overlap <-  chr11Overlap |>  
  filter(stratum == "inv11a")

inv11a.total <- NROW(chr11_inv11a)

inv11ab.chr11Overlap <-  chr11Overlap |>  
  filter(stratum =="inv11a&b")

inv11ab.total <- NROW(`chr11_inv11a&b`)

inv11b.chr11Overlap <-  chr11Overlap |>  
  filter(stratum =="inv11b")

inv11b.total <- NROW(chr11_inv11b)

anth.out.up <- out.chr11Overlap |> 
  filter(logFC.HvsCanther>2) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)

anth.out.down <- out.chr11Overlap |> 
  filter(logFC.HvsCanther< -2) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.out_up_num <- NROW(anth.out.up)
anth.out_down_num <- NROW(anth.out.down)

anth.hap.up <- hap.chr11Overlap |> 
  filter(logFC.HvsCanther<2) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.hap.down <- hap.chr11Overlap |> 
  filter(logFC.HvsCanther < -2) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.hap_up_num <- NROW(anth.hap.up)
anth.hap_down_num <- NROW(anth.hap.down)
  
anth.hapEDG.up <- hapEDG.chr11Overlap |> 
  filter(logFC.HvsCanther>2) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.hapEDG.down <- hapEDG.chr11Overlap |> 
  filter(logFC.HvsCanther< -2) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.hapEDG_up_num <- NROW(anth.hapEDG.up)
anth.hapEDG_down_num <-NROW(anth.hapEDG.down)

anth.inv11a.up <- inv11a.chr11Overlap |> 
  filter(logFC.HvsCanther>2) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.inv11a.down <- inv11a.chr11Overlap |> 
  filter(logFC.HvsCanther< -2) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)

anth.inv11a_up_num <- NROW(anth.inv11a.up)
anth.inv11a_down_num <-NROW(anth.inv11a.down)
  
anth.inv11ab.up <- inv11ab.chr11Overlap |> 
  filter(logFC.HvsCanther>2) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.inv11ab.down <- inv11ab.chr11Overlap |> 
  filter(logFC.HvsCanther< -2) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.inv11ab_up_num <- NROW(anth.inv11ab.up)
anth.inv11ab_down_num <- NROW(anth.inv11ab.down)

anth.inv11b.up <- inv11b.chr11Overlap |> 
  filter(logFC.HvsCanther>2) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.inv11b.down <- inv11b.chr11Overlap |> 
 filter(logFC.HvsCanther< -2) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.inv11b_up_num <- NROW(anth.inv11b.up)
anth.inv11b_down_num <- NROW(anth.inv11b.down)



x.chr11 <- c(anth.out_up_num, anth.out_down_num, anth.hap_up_num, anth.hap_down_num, anth.hapEDG_up_num, anth.hapEDG_down_num, anth.inv11a_up_num, anth.inv11a_down_num, anth.inv11ab_up_num, anth.inv11ab_down_num, anth.inv11b_up_num, anth.inv11b_down_num) 
n.chr11 <- c(out.total, out.total, hap.total, hap.total, hapEDG.total, hapEDG.total, inv11a.total, inv11a.total, inv11ab.total, inv11ab.total, inv11b.total, inv11b.total)


pairwise.prop.test(x.chr11, n.chr11)

chr11.stratum <- c("Out", "Out", "Haplotype", "Haplotype", "Haplotype EDG", "Haplotype EDG", "Inversion 11a", "Inversion 11a", "Inversion 11ab", "Inversion 11ab", "Inversion 11b", "Inversion 11b")
chr11.up_down <- c("Up Regulated", "Down Regulated", "Up Regulated", "Down Regulated", "Up Regulated", "Down Regulated", "Up Regulated", "Down Regulated", "Up Regulated", "Down Regulated", "Up Regulated", "Down Regulated")
chr11.values <- c(anth.out_up_num/out.total, anth.out_down_num/out.total, anth.hap_up_num/hap.total, anth.hap_down_num/hap.total, anth.hapEDG_up_num/hapEDG.total, anth.hapEDG_down_num/hapEDG.total, anth.inv11a_up_num/inv11a.total, anth.inv11a_down_num/inv11a.total, anth.inv11ab_up_num/inv11ab.total, anth.inv11ab_down_num/inv11ab.total, anth.inv11b_up_num/inv11b.total, anth.inv11b_down_num/inv11b.total)
chr11.stratum <- factor(chr11.stratum, levels = c("Out", "Haplotype", "Haplotype EDG", "Inversion 11a", "Inversion 11ab", "Inversion 11b"))

chr11.df <- data.frame(
  stratum = chr11.stratum,
  up_down = chr11.up_down,
  values = chr11.values
)
head(chr11.df)

ggplot(chr11.df, aes(x = stratum, y = values, fill = up_down)) +
  geom_bar(position = "dodge", stat = "identity") +
  scale_fill_manual(values = pairwise.colors)+
  labs(
    title = "Significantly differentially expressed genes in CHR 11 (logFC> abs(2))",
    x = "Chromsome 11 Stratum",
    y = "Proportion of Total Genes",
    fill = "Direction"
  ) +
  theme_minimal()

```

```{r}
### I have done this in a little bit of a lazy way, just removed he filtering step from above and retained everythign else, you will have to re run the whole bloc if you want to tweak the above figure, only difference is I piped all of this into chr11.df.all at the bottom

out.chr11Overlap <- chr11Overlap |> 
  filter(stratum=="out")

out.total <- NROW(chr11_out)
  

hap.chr11Overlap<- chr11Overlap |> 
  filter(stratum=="hap")

hap.total <- NROW(chr11_hap)

hapEDG.chr11Overlap <-  chr11Overlap |>  
  filter(stratum == "hap-EDG")

hapEDG.total <- NROW(`chr11_hap-EDG`)

inv11a.chr11Overlap <-  chr11Overlap |>  
  filter(stratum == "inv11a")

inv11a.total <- NROW(chr11_inv11a)

inv11ab.chr11Overlap <-  chr11Overlap |>  
  filter(stratum =="inv11a&b")

inv11ab.total <- NROW(`chr11_inv11a&b`)

inv11b.chr11Overlap <-  chr11Overlap |>  
  filter(stratum =="inv11b")

anth.out.up <- out.chr11Overlap |> 
  filter(logFC.HvsCanther>0) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)

anth.out.down <- out.chr11Overlap |> 
  filter(logFC.HvsCanther< 0) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.out_up_num <- NROW(anth.out.up)
anth.out_down_num <- NROW(anth.out.down)

anth.hap.up <- hap.chr11Overlap |> 
  filter(logFC.HvsCanther<0) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.hap.down <- hap.chr11Overlap |> 
  filter(logFC.HvsCanther < 0) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.hap_up_num <- NROW(anth.hap.up)
anth.hap_down_num <- NROW(anth.hap.down)
  
anth.hapEDG.up <- hapEDG.chr11Overlap |> 
  filter(logFC.HvsCanther>0) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.hapEDG.down <- hapEDG.chr11Overlap |> 
  filter(logFC.HvsCanther< 0) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.hapEDG_up_num <- NROW(anth.hapEDG.up)
anth.hapEDG_down_num <-NROW(anth.hapEDG.down)

anth.inv11a.up <- inv11a.chr11Overlap |> 
  filter(logFC.HvsCanther>0) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.inv11a.down <- inv11a.chr11Overlap |> 
  filter(logFC.HvsCanther< 0) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)

anth.inv11a_up_num <- NROW(anth.inv11a.up)
anth.inv11a_down_num <-NROW(anth.inv11a.down)
  
anth.inv11ab.up <- inv11ab.chr11Overlap |> 
  filter(logFC.HvsCanther>0) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.inv11ab.down <- inv11ab.chr11Overlap |> 
  filter(logFC.HvsCanther< 0) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.inv11ab_up_num <- NROW(anth.inv11ab.up)
anth.inv11ab_down_num <- NROW(anth.inv11ab.down)

anth.inv11b.up <- inv11b.chr11Overlap |> 
  filter(logFC.HvsCanther>0) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.inv11b.down <- inv11b.chr11Overlap |> 
 filter(logFC.HvsCanther< 0) |> 
  dplyr::select(IM62v4:logFC.HvsCanther, logCPM:FDR)
anth.inv11b_up_num <- NROW(anth.inv11b.up)
anth.inv11b_down_num <- NROW(anth.inv11b.down)



x.chr11 <- c(anth.out_up_num, anth.out_down_num, anth.hap_up_num, anth.hap_down_num, anth.hapEDG_up_num, anth.hapEDG_down_num, anth.inv11a_up_num, anth.inv11a_down_num, anth.inv11ab_up_num, anth.inv11ab_down_num, anth.inv11b_up_num, anth.inv11b_down_num) 
n.chr11 <- c(out.total, out.total, hap.total, hap.total, hapEDG.total, hapEDG.total, inv11a.total, inv11a.total, inv11ab.total, inv11ab.total, inv11b.total, inv11b.total)


pairwise.prop.test(x.chr11, n.chr11)

chr11.stratum <- c("Out", "Out", "Haplotype", "Haplotype", "Haplotype EDG", "Haplotype EDG", "Inversion 11a", "Inversion 11a", "Inversion 11ab", "Inversion 11ab", "Inversion 11b", "Inversion 11b")
chr11.up_down <- c("Up Regulated", "Down Regulated", "Up Regulated", "Down Regulated", "Up Regulated", "Down Regulated", "Up Regulated", "Down Regulated", "Up Regulated", "Down Regulated", "Up Regulated", "Down Regulated")
chr11.values <- c(anth.out_up_num/out.total, anth.out_down_num/out.total, anth.hap_up_num/hap.total, anth.hap_down_num/hap.total, anth.hapEDG_up_num/hapEDG.total, anth.hapEDG_down_num/hapEDG.total, anth.inv11a_up_num/inv11a.total, anth.inv11a_down_num/inv11a.total, anth.inv11ab_up_num/inv11ab.total, anth.inv11ab_down_num/inv11ab.total, anth.inv11b_up_num/inv11b.total, anth.inv11b_down_num/inv11b.total)
chr11.stratum <- factor(chr11.stratum, levels = c("Out", "Haplotype", "Haplotype EDG", "Inversion 11ab", "Inversion 11a", "Inversion 11b"))

chr11.df.all <- data.frame(
  stratum = chr11.stratum,
  up_down = chr11.up_down,
  values = chr11.values
)
pairwise.colors <- c("#fdb125","#fde725")
ggplot(chr11.df.all, aes(x = stratum, y = values, fill = up_down)) +
  geom_col(position = "dodge", stat = "identity") +
  scale_fill_manual(values = pairwise.colors)+
  labs(
    title = "All differentially expressed genes in CHR 11",
    x = "Chromsome 11 Stratum",
    y = "Proportion of Total Genes",
    fill = "Direction"
  ) +
  theme_minimal()
```




```{r}
###exploratory work before using splicejam for sashimi plots, testing with anther

###looks liek there is interesting gaps here in expresssinog and movement based off of logFC, 

View(chr11AntherOverlap)


ggplot(fitleredchr11Anther, mapping = aes(x=START, y=logFC)) + geom_point()



### need to retreive genome assemble file and convert to gtf and retreive splice junction file to pair with rna-seq reads and data 

#both packages neccessary for reading in and processing gtf files, Genomic 
BiocManager::install("GenomicFeatures")
library(GenomicFeatures)
BiocManager::install("txdbmaker")
library(txdbmaker)
BiocManager::install("rtracklayer")
library(rtracklayer)

library(devtools)

devtools::install_github("jmw86069/splicejam")
library(splicejam)
library(kableExtra)
mimgutGFF <- import("Mguttatusvar_IM62_797_v3.1.gene.gff3")
mimgut.annotations.TxDb<- makeTxDbFromGFF("Mguttatusvar_IM62_797_v3.1.gene.gff3", format = "gff3")


### created by adapting vignette from https://jmw86069.github.io/splicejam/articles/create-a-sashimi-plot.html

options("warn"=-1);
suppressPackageStartupMessages(library(splicejam));
suppressPackageStartupMessages(library(jamba));
suppressPackageStartupMessages(library(kableExtra));
if (suppressPackageStartupMessages(require(mimgut.annotations.TxDb))) {

   # First obtain exons by transcript
   exonsBymimgut <- exonsBy(mimgut.annotations.TxDb,
      by="tx",
      use.names=TRUE);
   values(exonsBymimgut@unlistData)$feature_type <- "exon";
   values(exonsBymimgut@unlistData)$subclass <- "exon";
   
   # For added insight, obtain CDS exons by transcript (optional)
   cdsBymimgut <- cdsBy(mimgut.annotations.TxDb,
      by="tx",
      use.names=TRUE);
   values(cdsBymimgut@unlistData)$feature_type <- "cds";
   values(cdsBymimgut@unlistData)$subclass <- "cds";
}


if (require(mimgut.annotations.TxDb)) {

   # Now prepare tx_name, gene_id, gene_name data.frame,
   # surprisingly difficult
   tx2geneMimGut <- suppressMessages(
      AnnotationDbi::select(mimgut.annotations.TxDb,
         keys(mimgut.annotations.TxDb, "GENEID"),
         columns=c("GENEID","TXNAME"),
         keytype="GENEID"
      )
   );
   tx2geneMimGut <- renameColumn(tx2geneMimGut,
      from=c("GENEID", "TXNAME", "TXTYPE"),
      to=c("gene_id", "transcript_id", "transcript_type"));

   # add gene_name using org.Mm.eg.db
   if (suppressPackageStartupMessages(require(org.Mm.eg.db))) {
      gene_ids <- values(genes(mimgut.annotations.TxDb))$gene_id;
      gene_namesL <- mget(gene_ids,
         org.Mm.egSYMBOL,
         ifnotfound=NA);
      ## Convert list to vector taking the first gene_name each
      ## (All genes should only have one SYMBOL but there is no
      ## hard constraint so we should make absolutely sure to
      ## use only one value per gene.)
      gene_names <- unlist(heads(S4Vectors::List(gene_namesL), 1));
      ## Replace NA with LOC# format
      ## Note we use gsub() to ensure the data fits the expected format
      if (any(is.na(gene_names))) {
         gene_na <- which(is.na(gene_names));
         gene_names[gene_na] <- gsub("^([0-9]+)$", "LOC\\1",
            names(gene_names[gene_na]));
      }
      tx2geneMimGut$gene_name <- gene_names[as.character(tx2geneMimGut$gene_id)];
   } else {
      ## If we have no gene annotations, use the gene_id values
      tx2geneMimGut$gene_name <- as.character(tx2geneMimGut$gene_id);
   }
   # print the first 20 rows to show the content
   print(head(tx2geneMimGut, 20));
}
#> Loading required package: mimgut.annotations.TxDb




```
```{r}

```


```{r}
## more packages + libraries :(
BiocManager::install("org.At.tair.db")
BiocManager::install("AnnotationDbi")
library(org.At.tair.db)
library(AnnotationDbi)
```


```{r}
## whole genome translation into athal and then enrichment w GO terms
athal_mimgut_orthologs <- read_tsv("Athal mimgut orthologs.txt")

## normalizes format to facilitate joining (as above)
allDEGs.mapping <- as_tibble(testDGE$genes) 
allDEGs.mapping <- allDEGs.mapping |> 
  mutate(GENE= str_remove(GENE,".v3.1")) |> 
  mutate(GENE= str_remove(GENE," "))

## making list of all DEGs that also contains the athal orthologs for GO enrichment
allDEGsAthalMimgut <- inner_join(athal_mimgut_orthologs, allDEGs.mapping, by = join_by(`Gene Name` == GENE))
##Hi Ren, started orking on this, to me, the above inner_join is what we are looking for, and these two operations have different dimensions as the merge keeps the genes that do not have matcehs and fills them with an NA, you probably already know this, just wanted to write this to remind myself in the future

allDEGsAthalMimgutTEST <- merge(allDEGs.mapping, athal_mimgut_orthologs, by.x = "GENE", by.y = "Gene Name", all.x = TRUE)

dim(athal_mimgut_orthologs)
dim(allDEGs.mapping)
dim(allDEGsAthalMimgut)
dim(allDEGsAthalMimgutTEST)

##fixing the name from TAIR (ie. AT1G61140) format to ENTREZID (ie. 842407)
athalGO <- bitr(allDEGsAthalMimgut$`Ortholog Gene Name`,
                fromType = "TAIR",
                toType = "ENTREZID",
                OrgDb = org.At.tair.db)

go_results <- enrichGO(gene = as.vector(athalGO$ENTREZID),
                       OrgDb = org.At.tair.db,
                       keyType = "ENTREZID",
                       ont = "BP",
                       pAdjustMethod = "BH",
                       pvalueCutoff = 0.05,
                       qvalueCutoff = 0.2)

go_genes <- strsplit(go_results$geneID, "/")[[1]]
print(go_genes)
```

```{r}
#Building on ren's code and using profiler/gost
#https://biit.cs.ut.ee/gprofiler/gost

#Closing up shop june 3, confused, defeated, %in% not workign for anythign but bud, tried using intersect, they have different values? will continue working

bud.precursor <- subset(allDEGsAthalMimgut$`Gene Name`, budTags$table$FDR < 0.05 & bud.logfc$abs_logFC>2)
bud.gost <- allDEGsAthalMimgut |> 
  filter(`Gene Name` %in% bud.precursor)
bud.gost.test <- intersect(allDEGsAthalMimgut$`Gene Name`, bud.precursor)

view(bud.gost)
writeLines(bud.gost$`Ortholog Gene Name`, "budAthal.txt")

leaf.precursor <- subset(allDEGsAthalMimgut$`Gene Name`, leafTags$table$FDR < 0.05 & leaf.logfc$abs_logFC>2)
leaf.gost <- intersect(allDEGsAthalMimgut$`Gene Name`,leaf.precursor)

writeLines(leaf.gost$`Ortholog Gene Name`, "leafAthal.txt")

anth.precursor <- subset(allDEGsAthalMimgut$`Gene Name`, leafTags$table$FDR < 0.05 & leaf.logfc$abs_logFC>2)
anth.gost <- intersect(allDEGsAthalMimgut$`Gene Name`, anth.precursor)
writeLines(anth.gost$`Ortholog Gene Name`, "anthAthal.txt")

ovary.precursor <- subset(allDEGsAthalMimgut$`Gene Name`, ovaryTags$table$FDR < 0.05 & ovary.logfc$abs_logFC>2)
ovary.gost <- intersect(allDEGsAthalMimgut$`Gene Name`, ovary.precursor)
writeLines(ovary.gost$`Ortholog Gene Name`, "ovaryAthal.txt")


```

